minx = float('inf')
miny = float('inf')
minz = float('inf')
maxx = float('-inf')
maxy = float('-inf')
maxz = float('-inf')
while (s := input().strip()) != "":
	x, y, z = map(float, s.split(','))
	minx = min(minx, x)
	maxx = max(maxx, x)
	minz = min(minz, z)
	maxz = max(maxz, z)
	miny = min(miny, y)
	maxy = max(maxy, y)
v = (maxx - minx) * (maxy - miny) * (maxz - minz)
print(v)
